#org_shortened

# wno_data2$org_shortened <- wno_data2$org
# wno_data2$org_shortened <- recode_factor(wno_data2$org_shortened,
#                                           `Alabama League of the South` = "ALS",
#                                           `American Friends of the British National Party` = "AFBNP",
#                                           `American Immigration Control` = "AIC",
#                                           `American Nationalist Federation` = "ANF",
#                                           `American Policy Institute` = "API",
#                                           `Anglo-Saxon Christian Patriots` = "ASCP",
#                                           `Calvary Temple Baptist Church` = "CTBP",
#                                           `Carolina Knights of the Ku Klux Klan` = "Carolina KKK",
#                                           `Christian Civil Liberties Association` = "CCLA",
#                                           `Christian Defense League` = "CDL",
#                                           `Christian Israel Fellowship of Virginia` = "CIFV",
#                                           `Christian Separatist Church Society` = "CSCS",
#                                           `Church of Jesus Christ` = "CJC",
#                                           `Confederate Hammer Skins` = "CHS",
#                                           `Confederate Knights of the Ku Klux Klan` = "Confederate KKK",
#                                           `Confederate Knights of America` = "CKA",
#                                           `Confederate States Research Centre` = "CSRC",
#                                           `Confederate White Knights` = "CWK",
#                                           `Crusade for Christ and Country` = "CCC",
#                                           `David Duke/Euro-American Unity and Rights` = "EURO",
#                                           `League of the South` = "LS",
#                                           `Mission of the King` = "MK",
#                                           `National Alliance` = "NA",
#                                           `Nordwave` = "Nordwave",
#                                           `National Association for the Advancement of White People` = "NAAWP",
#                                           `Nationalist Free Press` = "NFP",
#                                           `Patriot's Defense Foundation/CAUSE` = "PFD/CAUSE",
#                                           `Sons of Confederate Veterans/Foundation for the Preservation of American Culture` = "SCV",
#                                           `Special Forces Underground` = "SFU",
#                                           `The First Freedom` = "FF",
#                                           `The Knights of the Ku Klux Klan/The Knights Party` = "Knights Party",
#                                           `Thunderbolt LLC` = "Thunderbolt",
#                                           `Virginia Christian Israelites` = "VCI",
#                                           `Yahweh Elohei (The Almighty Covenant One of) Israel` = "YE"
# )